spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/arigatouAirlines
    username: root
    password: Thang2005
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # 🟢 Thêm dòng này
  mail:
    host: smtp.gmail.com
    port: 587
    username: daolelongvu1000@gmail.com
    password: 0986770920
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

jwt:
  signerKey: "fAhsFQLtyhPPawzKmGDEU/IDeBpV7nGnIaQIWYZCzh8qGSb+ETsbFOoMfwfNsUgA"

gemini:
  api-key: AIzaSyCg-P6IjWEsC53j_0UGvZkBCpt5-Fc8PCo
  model: "gemini-1.5-flash-latest"

server:
    port: 8080
    servlet:
        context-path: /arigatouAirlines
